### ISSUE TITLE
Axios dependency

### ISSUE THREAD

**Issue by caveofjulian** [simmodev/vue-media-upload#5]
Hi there, cool library! I would love to use this in Vue 3, got it on display also but it complains about axios not being defined. I provided the full API path in the "server" tag. Do I have to initialize something in axios?

**Comment by dbeis** [comment]
@caveofjulian 
Hello, 
i get the same error. I do not know how to fix it but to temporarily bypass it you can do some kind of global import of axios.

Check here https://stackoverflow.com/questions/51374367/axios-is-not-defined-in-vue-js-cli .

**Comment by s1modev** [comment]
Since i am testing the package on a Laravel project, i don't get this error.
I just made a new commit, where i tried to fix that .
Please make sure that you are using the last version (1.0.4 for now) and tell me if this problem still occurs to you.

Thanks for your feedback!
